server:
  port: 8082

spring:
  application:
    name: service-transaction

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: "default"

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/services_emplo_db
    username: postgres
    password: postgres
    # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"

    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

topic:
  name: employer_service-event-topic

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


