server:
  error:
    whitelabel:
      enabled: true
  port: 8081

  #  spring:
  #    datasource:
  #      url: jdbc:mysql://localhost:3306/myclient
  #      username: root
  #      password:
  #      driver-class-name: com.mysql.cj.jdbc.Driver

  #jpa:
  #  hibernate:
  #    ddl-auto: update
  #  properties:
  #    hibernate:
  #      dialect: org.hibernate.dialect.MySQL8Dialect
  spring:
    profiles:
      active: development

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Employer
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    spring:
      datasource:
        jpa:
          generate-ddl: 'true'
          open-in-view: 'false'
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" to "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#server:
#  port: 8081
#spring:
#  application:
#    name: user-service
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/myUsersMemory
#    username: postgres
#    password: postgres
#    # JPA properties
#  jpa:
#    hibernate:
#      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
#
#    show-sql: true
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    open-in-view: false
#    generate-ddl: true




