server:
  port: 8081
spring:
  application:
    name: employer-service
  datasource:
    url: jdbc:postgresql://localhost:5432/Employer
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    spring:
      datasource:
        jpa:
          generate-ddl: 'true'
          open-in-view: 'false'
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" to "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

topic:
  name: employer-event-topic



